import { test, expect } from '@playwright/test';

test('Increasing income with quarterly payments', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'GET STARTED' }).first().click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Dropdown' }).click();
  await page.getByRole('button', { name: 'Missouri' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Single' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$8000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$6000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$8,0000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Increase' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button No' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$100');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('$100');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$50');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('$50');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Pay each quarter' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('dmgreen10@gmail.com');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').fill('password');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.goto('http://localhost:5173/dashboard');
});