import { test, expect } from '@playwright/test';

test('Decreasing income with quarterly payments', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'GET STARTED' }).nth(1).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox', { name: 'State' }).click();
  await page.getByRole('button', { name: 'Minnesota' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Married Filing Jointly' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$9000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$7000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$9,5000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Decrease' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$7,0000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$500');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('$250');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('$300');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$500');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$200');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$50');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('$100');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$30');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('$10');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Pay each quarter' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('dmgreen10@gmail.com');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').fill('password');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.goto('http://localhost:5173/dashboard');
});