import { test, expect } from '@playwright/test';

test('Decreasing income with single payments', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'GET STARTED' }).nth(1).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox', { name: 'State' }).click();
  await page.getByRole('button', { name: 'Wisconsin' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Qualifying Widow' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$60,00');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$4000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$6,0000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$6,0000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Decrease' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$5,0000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('$200');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$800');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('0');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$80');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('$20');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('$40');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('$60');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Pay in single' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('dmgreen10@gmail.c');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').press('Shift+Tab');
  await page.locator('input[type="email"]').press('ArrowRight');
  await page.locator('input[type="email"]').fill('dmgreen10@gmail.com');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').fill('password');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.goto('http://localhost:5173/dashboard');
});