import { test, expect } from '@playwright/test';

test('Increasing income with single payments', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'GET STARTED' }).nth(1).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox', { name: 'State' }).click();
  await page.getByRole('button', { name: 'Virginia', exact: true }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Head of Household' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$5000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$3000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('$5,0000');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Stay about the' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Yes' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button No' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('0');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('0');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('0');
  await page.getByRole('textbox').first().press('Tab');
  await page.getByRole('textbox').nth(1).fill('0');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'Radio button Pay in single' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('dmgreen10@gmail.com');
  await page.locator('input[type="email"]').press('Tab');
  await page.locator('input[type="password"]').fill('password');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.goto('http://localhost:5173/dashboard');
});